### PR TITLE
Fix ext.sm.forminputs path

### LINKED ISSUE #84: Form input broken
We were using a input field for coordinates in Semantic Forms, like
```text
{{{field|Coordinates|input type=googlemaps|default={{PAGENAME}}|property=Coordinates|mandatory}}}
```
(I think "Coordinates" here is a variable specified in the own system)

This input field loaded with Semantic Maps 3.3 but didn't load with 3.4.0-alpha.
Maybe you could check if some change caused a problem.
BTW: input type didn't work with leaflet or openlayers  in the older versions anyway, so you always had to use google maps.

### PR DESCRIPTION
**Pull request by PeterTheOne**
fix #84

### CODE REVIEW

File: SemanticMaps.php [hunk 1]
```diff
@@ -67,10 +67,8 @@ public static function initExtension() {
 		include_once __DIR__ . '/src/queryprinters/SM_QueryPrinters.php';
 
 		$moduleTemplate = [
-				'position' => 'bottom',
-				'localBasePath' => __DIR__ . '/src',
-				'remoteExtPath' => 'SemanticMaps/src',
-				'group' => 'ext.semanticmaps',
+			'position' => 'bottom',
+			'group' => 'ext.semanticmaps',
```
Comment (JeroenDeDauw) [inline SemanticMaps.php]: Actually this `$moduleTemplate` thing is not paying for itself. Inlining would be simpler and less error prone.

**Comment by JeroenDeDauw** [comment]
The broken CI is annoying...

File: SemanticMaps.php (hunk 1 above)
Comment (PeterTheOne) [inline SemanticMaps.php]: Yes, I expected it to be array merge but it was array union.. :/
